// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie-service.proto

package br.com.til.grpcflix.models.movie;

public interface MovieSearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieSearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MovieDTO movie = 1;</code>
   */
  java.util.List<br.com.til.grpcflix.models.movie.MovieDTO> 
      getMovieList();
  /**
   * <code>repeated .MovieDTO movie = 1;</code>
   */
  br.com.til.grpcflix.models.movie.MovieDTO getMovie(int index);
  /**
   * <code>repeated .MovieDTO movie = 1;</code>
   */
  int getMovieCount();
  /**
   * <code>repeated .MovieDTO movie = 1;</code>
   */
  java.util.List<? extends br.com.til.grpcflix.models.movie.MovieDTOOrBuilder> 
      getMovieOrBuilderList();
  /**
   * <code>repeated .MovieDTO movie = 1;</code>
   */
  br.com.til.grpcflix.models.movie.MovieDTOOrBuilder getMovieOrBuilder(
      int index);
}
