// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-service.proto

package br.com.til.grpcflix.models.user;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string login_id = 1;</code>
   */
  java.lang.String getLoginId();
  /**
   * <code>string login_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginIdBytes();

  /**
   * <code>string user_name = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>.common.Genre genre = 3;</code>
   */
  int getGenreValue();
  /**
   * <code>.common.Genre genre = 3;</code>
   */
  br.com.til.grpcflix.common.Genre getGenre();
}
