// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-service.proto

package br.com.til.grpcflix.models.user;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserGenreUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserGenreUpdateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user-service.proto\032\023common/common.prot" +
      "o\"%\n\021UserSearchRequest\022\020\n\010login_id\030\001 \001(\t" +
      "\"Q\n\014UserResponse\022\020\n\010login_id\030\001 \001(\t\022\021\n\tus" +
      "er_name\030\002 \001(\t\022\034\n\005genre\030\003 \001(\0162\r.common.Ge" +
      "nre\"H\n\026UserGenreUpdateRequest\022\020\n\010login_i" +
      "d\030\001 \001(\t\022\034\n\005genre\030\002 \001(\0162\r.common.Genre2|\n" +
      "\013UserService\0222\n\rgetUserGenrer\022\022.UserSear" +
      "chRequest\032\r.UserResponse\0229\n\017updateUserGe" +
      "nre\022\027.UserGenreUpdateRequest\032\r.UserRespo" +
      "nseB#\n\037br.com.til.grpcflix.models.userP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          br.com.til.grpcflix.common.Common.getDescriptor(),
        }, assigner);
    internal_static_UserSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserSearchRequest_descriptor,
        new java.lang.String[] { "LoginId", });
    internal_static_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserResponse_descriptor,
        new java.lang.String[] { "LoginId", "UserName", "Genre", });
    internal_static_UserGenreUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserGenreUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserGenreUpdateRequest_descriptor,
        new java.lang.String[] { "LoginId", "Genre", });
    br.com.til.grpcflix.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
